#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1ubuntu2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/regolith-debootstick-setup" ] ; then
	chmod -x "/etc/init.d/regolith-debootstick-setup" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d regolith-debootstick-setup remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.24.1ubuntu2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
