#!/bin/sh
set -e
# Automatically added by dh_installinit/13.24.1ubuntu2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/regolith-debootstick-setup" ] ; then
	invoke-rc.d regolith-debootstick-setup stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.24.1ubuntu2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'regolith-debootstick-setup.service' >/dev/null || true
fi
# End automatically added section
